USE master;
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = 'QLCH')
BEGIN
    ALTER DATABASE QLCH SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE QLCH;
END
GO
CREATE DATABASE QLCH;
GO

-- Sử dụng database mới tạo
USE QLCH;
GO

-- Drop bảng theo thứ tự tránh lỗi khóa ngoại
IF OBJECT_ID('ChiTietHoaDon', 'U') IS NOT NULL DROP TABLE ChiTietHoaDon;
IF OBJECT_ID('HoaDon', 'U') IS NOT NULL DROP TABLE HoaDon;
IF OBJECT_ID('TaiKhoan', 'U') IS NOT NULL DROP TABLE TaiKhoan;
IF OBJECT_ID('SanPham', 'U') IS NOT NULL DROP TABLE SanPham;
IF OBJECT_ID('LoaiSP', 'U') IS NOT NULL DROP TABLE LoaiSP;
IF OBJECT_ID('KhachHang', 'U') IS NOT NULL DROP TABLE KhachHang;
IF OBJECT_ID('NhanVien', 'U') IS NOT NULL DROP TABLE NhanVien;
-- Bảng LoaiSP
CREATE TABLE LoaiSP (
    MaLoai CHAR(10) PRIMARY KEY,
    TenLoai NVARCHAR(30) NOT NULL
);

-- Bảng SanPham
CREATE TABLE SanPham (
    MaSP CHAR(10) PRIMARY KEY,
    MaLoai CHAR(10) NOT NULL,
    TenSP NVARCHAR(30) NOT NULL,
    DonGia DECIMAL(18,2) NOT NULL,
    SoLuongTon INT NOT NULL,
    MoTa NVARCHAR(255) NULL,
    CONSTRAINT FK_SanPham_LoaiSP FOREIGN KEY (MaLoai) REFERENCES LoaiSP(MaLoai)
);

-- Bảng KhachHang
CREATE TABLE KhachHang (
    MaKH CHAR(10) PRIMARY KEY,
    TenKH NVARCHAR(30) NOT NULL,
    SDT CHAR(10) NOT NULL,
    DiaChi NVARCHAR(100) NULL
);

-- Bảng NhanVien
CREATE TABLE NhanVien (
    MaNV CHAR(10) PRIMARY KEY,
    TenNV NVARCHAR(30) NOT NULL,
    SDT CHAR(10) NOT NULL,
    DiaChi NVARCHAR(100) NULL
);

-- Bảng TaiKhoan
CREATE TABLE TaiKhoan (
    TenDangNhap NVARCHAR(50) PRIMARY KEY,
    MatKhau NVARCHAR(256) NOT NULL,
    MaNV CHAR(10) NOT NULL,
    CONSTRAINT FK_TaiKhoan_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

-- Bảng HoaDon
CREATE TABLE HoaDon (
    MaHD CHAR(10) PRIMARY KEY,
    MaKH CHAR(10) NOT NULL,
    MaNV CHAR(10) NOT NULL,
    NgayLap DATE NOT NULL,
    GiaTien DECIMAL(18,2) NOT NULL,
    CONSTRAINT FK_HoaDon_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
    CONSTRAINT FK_HoaDon_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

-- Bảng ChiTietHoaDon
CREATE TABLE ChiTietHoaDon (
    MaHD CHAR(10) NOT NULL,
    MaSP CHAR(10) NOT NULL,
    SoLuong INT NOT NULL,
    DonGia DECIMAL(18,2) NOT NULL,
    PRIMARY KEY (MaHD, MaSP),
    CONSTRAINT FK_CTHD_HoaDon FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD),
    CONSTRAINT FK_CTHD_SanPham FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);
